# Generated by Django 3.1.7 on 2021-02-26 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EndOf', '0006_auto_20210226_0410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speech',
            name='author',
        ),
        migrations.AlterField(
            model_name='speech',
            name='Speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
